name: 'ARTIFACT TO UNZIP'
description: 'Download and Unzip an Node Artifact'
inputs:
  production:
    description: 'Is this a production build?'
    required: true
    default: 'true'
  addIgnore:
    description: 'Add Ignore?'
    required: true
    default: 'true'
runs:
  using: "composite"
  steps:
  - name: Download a package
    uses: Bhacaz/checkout-files@master
    with:
      files: package.json
      token: ${{ github.token }}
  - name: GET VERSION
    id: package-version
    uses: martinbeentjes/npm-get-version-action@master
  - name: 'Set Production:'
    run: echo "PROD=$(${{ inputs.production == 'true' }} && echo '' || echo '-s')" >> $GITHUB_ENV
    shell: bash
  - name: Download a single artifact
    if: ${{ github.event.workflow_run.workflow_id }}
    uses: dawidd6/action-download-artifact@master
    with:
      workflow: ${{ github.event.workflow_run.workflow_id }}
  - name: Download a single artifact
    if: ${{ !github.event.workflow_run.workflow_id }}
    uses: actions/download-artifact@main
    with:
      path: ${{ steps.package-version.outputs.current-version }}${{ env.PROD }}/${{ steps.package-version.outputs.current-version }}${{ env.PROD }}.zip
  - name: Add Ignore
    if: ${{ inputs.addIgnore == 'true' }}
    run: echo '${{ steps.package-version.outputs.current-version }}*' >> .npmignore
    shell: bash
  - name: Print
    run: ls
    shell: bash
  - name: Print ${{ steps.package-version.outputs.current-version }}
    run: ls ${{ steps.package-version.outputs.current-version }}
    shell: bash
  - name: Extract some files
    run: 7z x ${{ steps.package-version.outputs.current-version }}${{ env.PROD }}/${{ steps.package-version.outputs.current-version }}${{ env.PROD }}.zip -aoa
    shell: bash
  - name: Print end
    run: ls
    shell: bash
  - name: Print ${{ steps.package-version.outputs.current-version }} end
    run: ls ${{ steps.package-version.outputs.current-version }}
    shell: bash

