name: 'ARTIFACT TO UNZIP'
description: 'Download and Unzip an Node Artifact'
inputs:
  production:
    description: 'Is this a production build?'
    required: true
    default: 'true'
runs:
  using: "composite"
  steps:
  - name: GET VERSION
    id: package-version
    uses: martinbeentjes/npm-get-version-action@master
  - name: 'Set Production:'
    run: echo "PROD=$(${{ inputs.production == 'true' }} && echo '' || echo '-s')" >> $GITHUB_ENV
    shell: bash
  - name: Download a single artifact
    uses: actions/download-artifact@v2
  - name: Extract some files
    run: 7z x ${{ steps.package-version.outputs.current-version }}${{ env.PROD }}.zip -aoa
    shell: bash

